### ISSUE TITLE
??

### ISSUE THREAD

**Issue by FrostyHacker** [geokar2006/ByNameModding#1]
based on this?
https://github.com/MJx0/IL2CppResolver

**Comment by geokar2006** [comment]
No, IL2CppResolver finding il2cpp_resolve_icall by signature in libil2cpp.so, but signature is old or IL2CppResolver has bug. ByNameModding find il2cpp_resolve_icall by name from libil2cpp.so. I just took an example from IL2CppResolver, because it working with ByNameModding get_Method too.

**Comment by ozMod** [comment]
![image](https://user-images.githubusercontent.com/80401984/144440647-90e6e792-b1a8-444d-9387-e286795fda7b.png)
I found this one with IDA. Can I use it with dlsym? like 
void* (*il2cpp_resolve_icall_0)(const char *);
il2cpp_resolve_icall_0 = (void*(*)(const char *)) dlsym(get_il2cpp(), "il2cpp_resolve_icall_0");

**Comment by geokar2006** [comment]
> 

Methods with _0 not exported you can't get it using dlsym.

**Comment by geokar2006** [comment]
> ![image](https://user-images.githubusercontent.com/80401984/144440647-90e6e792-b1a8-444d-9387-e286795fda7b.png) I found this one with IDA. Can I use it with dlsym? like
> 
> ```
> #define targetLibName OBFUSCATE("libil2cpp.so")
> 
> void *get_il2cpp() {
>     void *module = 0;
>     while (!module) {
>         module = dlopen(targetLibName, RTLD_LAZY);
>     }
>     return module;
> }
> 
> void* (*il2cpp_resolve_icall_0)(const char *);
> 
> il2cpp_resolve_icall_0 = (void * (*)(const char *)) dlsym(get_il2cpp(), "il2cpp_resolve_icall_0");
>     const char *dlsym_error = dlerror();
>  if(dlsym_error){
>         LOGE("Cannot load symbol 'il2cpp_resolve_icall_0': %s", dlsym_error);
> }
> ```
> 
> edit - it works, just needed to remove _0. But i dont know why but the following result is happens only on BlueStacks 5 emulator, on others and devices its working fine:
> 
> ![image](https://user-images.githubusercontent.com/80401984/144450718-fd0d7d1c-4f59-46da-8881-04ab01c3adbc.png)
> 
> I even didnt put glFramebufferTexture. I dont know why it changes parameter of dlsym somehow.

Methods with _0 not exported you can't get it using dlsym.
