### ISSUE TITLE
How to LoadClass (inner class)

### ISSUE THREAD

**Issue by im-baydroid** [geokar2006/ByNameModding#12]
I want to load class `Setting`
```c++
//namespace :
public class Game {
   public class Setting{
   }
}
//dump.cs
//namespace :
public class Game.Setting{
}
```
I tried `LoadClass("","Game.Setting")` and `LoadClass("","Game::Setting")` but error

**Comment by geokar2006** [comment]
At this time use LoadClass("","Setting") or LoadClass::GetLC_ByClassAndMethodName("", "Setting", "Any method name from your Settings class"). Maybe later I add a better way to get inner classes.

**Comment by im-baydroid** [comment]
i got the solution, use  `/` 
like this:
```c++
auto GSetting = LoadClass("","Game/Setting");
```
