### ISSUE TITLE
Blue screen

### ISSUE THREAD

**Issue by chiteroman** [geokar2006/ByNameModding#17]
Hello, I add BNM to LGL mod template but when the game is loading the screen becomes blue:
![image](https://user-images.githubusercontent.com/98092901/185789446-2f26292b-f5bf-49b7-9d88-6a8622e1d1ce.png)

I'm using Dobby and I don't have any hook, just adding BNM.cpp to Android.mk this happen. Any solution?

**Comment by chiteroman** [comment]
In armeabi-v7a works but in arm64 not

**Comment by geokar2006** [comment]
Can you send game name and BNM logs (tag: ByNameModding)?

**Comment by geokar2006** [comment]
Fixed in this update
