### ISSUE TITLE
How to hook classes with  : such as   battleperformancecommandcard: basemonobehavior

### ISSUE THREAD

**Issue by oobbb** [geokar2006/ByNameModding#18]
This is how I write it now

auto bsvtd = LoadClass("", "BattlePerformanceCommandCard:BaseMonoBehaviour");
    HOOK(bsvtd.GetMethodOffsetByName("updateCardMag", 0), fp, &old_fp);
    HOOK(bsvtd.GetMethodOffsetByName("GetBaseCommandCard", 0), up, &old_up);

But it will cause the game to jam
Please help me

**Comment by YummyBacon5** [comment]
Try without the `&` for the old function

**Comment by geokar2006** [comment]
@oobbb, HOOK automatically add `&` to old method. Use it without `&`.
