### ISSUE TITLE
unity2019.4.30 crashed 

### ISSUE THREAD

**Issue by nzcv** [geokar2006/ByNameModding#20]
09-06 13:55:25.288 28762 28813 E CRASH   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-06 13:55:25.288 28762 28813 E CRASH   : Version '2019.4.30f1 (0)', Build type 'Development', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
09-06 13:55:25.288 28762 28813 E CRASH   : Build fingerprint: 'OnePlus/OnePlus7T_CH/OnePlus7T:10/QKQ1.190716.003/2001030004:user/release-keys'
09-06 13:55:25.288 28762 28813 E CRASH   : Revision: '0'
09-06 13:55:25.288 28762 28813 E CRASH   : ABI: 'arm64'
09-06 13:55:25.288 28762 28813 E CRASH   : Timestamp: 2022-09-06 13:55:25+0800
09-06 13:55:25.288 28762 28813 E CRASH   : pid: 28762, tid: 28813, name: .memLeakPatched  >>> com.king3soft.memLeakPatched <<<
09-06 13:55:25.288 28762 28813 E CRASH   : uid: 10285
09-06 13:55:25.288 28762 28813 E CRASH   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
09-06 13:55:25.288 28762 28813 E CRASH   :     x0  0000000000000000  x1  000000000000708d  x2  0000000000000006  x3  0000007a9b4f99b0
09-06 13:55:25.288 28762 28813 E CRASH   :     x4  fefeff7a8aff7164  x5  fefeff7a8aff7164  x6  fefeff7a8aff7164  x7  7f7f7f7fff7f7f7f
09-06 13:55:25.288 28762 28813 E CRASH   :     x8  00000000000000f0  x9  f0cee28690d62610  x10 0000000000000001  x11 0000000000000000
09-06 13:55:25.288 28762 28813 E CRASH   :     x12 fffffff0fffffbdf  x13 000000006316e0cd  x14 000e40e31c1a2558  x15 00003c0b4c7a664d
09-06 13:55:25.288 28762 28813 E CRASH   :     x16 0000007b8c1a9738  x17 0000007b8c187be0  x18 0000000000000005  x19 000000000000705a
09-06 13:55:25.288 28762 28813 E CRASH   :     x20 000000000000708d  x21 00000000ffffffff  x22 ffffff80ffffffc8  x23 0000007a9b4f9c00
09-06 13:55:25.288 28762 28813 E CRASH   :     x24 0000007a9b4f9ae0  x25 0000007a9b4f9b20  x26 0000007a9b4fc020  x27 0000007b8e766020
09-06 13:55:25.288 28762 28813 E CRASH   :     x28 0000007a9b51b00c  x29 0000007a9b4f9a50
09-06 13:55:25.288 28762 28813 E CRASH   :     sp  0000007a9b4f9990  lr  0000007b8c139404  pc  0000007b8c139430
09-06 13:55:25.288 28762 28813 E CRASH   :
09-06 13:55:25.288 28762 28813 E CRASH   : backtrace:
09-06 13:55:25.288 28762 28813 E CRASH   :       #00 pc 0000000000073430  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: a2584ee8458a61d422edf24b4cd23b78)
09-06 13:55:25.288 28762 28813 E CRASH   :       #01 pc 0000000000615b48  /data/app/com.king3soft.memLeakPatched-y_np4plRNtso3GTV1RUb-Q==/lib/arm64/libil2cpp.so (std::set_unexpected(void (*)())) (BuildId: 2fd6aa9d2105ba462127e2f66fc8f0aad40aa320)
09-06 13:55:25.289 28762 28813 E CRASH   :       #02 pc 0000000000615cc4  /data/app/com.king3soft.memLeakPatched-y_np4plRNtso3GTV1RUb-Q==/lib/arm64/libil2cpp.so (demangling_unexpected_handler()) (BuildId: 2fd6aa9d2105ba462127e2f66fc8f0aad40aa320)
09-06 13:55:25.289 28762 28813 E CRASH   :       #03 pc 0000000000612f54  /data/app/com.king3soft.memLeakPatched-y_np4plRNtso3GTV1RUb-Q==/lib/arm64/libil2cpp.so (std::__terminate(void (*)())+12) (BuildId: 2fd6aa9d2105ba462127e2f66fc8f0aad40aa320)
09-06 13:55:25.289 28762 28813 E CRASH   :       #04 pc 0000000000612638  /data/app/com.king3soft.memLeakPatched-y_np4plRNtso3GTV1RUb-Q==/lib/arm64/libil2cpp.so (__cxa_get_exception_ptr) (BuildId: 2fd6aa9d2105ba462127e2f66fc8f0aad40aa320)
09-06 13:55:25.289 28762 28813 E CRASH   :       #05 pc 00000000006125b8  /data/app/com.king3soft.memLeakPatched-y_np4plRNtso3GTV1RUb-Q==/lib/arm64/libil2cpp.so (__cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)) (BuildId: 2fd6aa9d2105ba462127e2f66fc8f0aad40aa320)
09-06 13:55:25.289 28762 28813 E CRASH   :       #06 pc 00000000004c1b74  /data/app/com.king3soft.memLeakPatched-y_np4plRNtso3GTV1RUb-Q==/lib/arm64/libil2cpp.so (il2cpp::vm::Exception::Raise(Il2CppException*, MethodInfo*)+96) (BuildId: 2fd6aa9d2105ba462127e2f66fc8f0aad40aa320)
09-06 13:55:25.289 28762 28813 E CRASH   :       #07 pc 0000000000447768  /data/app/com.king3soft.memLeakPatched-y_np4plRNtso3GTV1RUb-Q==/lib/arm64/libil2cpp.so (il2cpp_exception_from_name_msg) (BuildId: 2fd6aa9d2105ba462127e2f66fc8f0aad40aa320)
09-06 13:55:25.289 28762 28813 E CRASH   :       #08 pc 0000000000c33110  /data/app/com.king3soft.memLeakPatched-y_np4plRNtso3GTV1RUb-Q==/lib/arm64/libunity.so (ScriptingExceptionPtr::GetBackendPtr() const) (BuildId: 4add47ca148d41fe94977db941b2e4c3af1cd559)
09-06 13:55:25.289 28762 28813 E CRASH   :       #09 pc 0000000000c42f20  /data/app/com.king3soft.memLeakPatched-y_np4plRNtso3GTV1RUb-Q==/lib/arm64/libunity.so (scripting_raise_exception(ScriptingExceptionPtr)+56) (BuildId: 4add47ca148d41fe94977db941b2e4c3af1cd559)
09-06 13:55:25.289 28762 28813 E CRASH   :       #10 pc 0000000000c43730  /data/app/com.king3soft.memLeakPatched-y_np4plRNtso3GTV1RUb-Q==/lib/arm64/libunity.so (CreateUnityExceptionCommonMessage(char const*)) (BuildId: 4add47ca148d41fe94977db941b2e4c3af1cd559)
09-06 13:55:25.289 28762 28813 E CRASH   :       #11 pc 0000000000c475bc  /data/app/com.king3soft.memLeakPatched-y_np4plRNtso3GTV1RUb-Q==/lib/arm64/libunity.so (ThreadAndSerializationSafeCheck::ReportError(int, char const*, ...)) (BuildId: 4add47ca148d41fe94977db941b2e4c3af1cd559)
09-06 13:55:25.289 28762 28813 E CRASH   :       #12 pc 0000000000c47630  /data/app/com.king3soft.memLeakPatched-y_np4plRNtso3GTV1RUb-Q==/lib/arm64/libunity.so (TextAsset::TextAsset(MemLabelId, ObjectCreationMode)) (BuildId: 4add47ca148d41fe94977db941b2e4c3af1cd559)
09-06 13:55:25.289 28762 28813 E CRASH   :       #13 pc 0000000000c45d04  /data/app/com.king3soft.memLeakPatched-y_np4plRNtso3GTV1RUb-Q==/lib/arm64/libunity.so (ThreadAndSerializationSafeCheck::ReportError(char const*)+76) (BuildId: 4add47ca148d41fe94977db941b2e4c3af1cd559)
09-06 13:55:25.289 28762 28813 E CRASH   :       #14 pc 0000000000d16964  /data/app/com.king3soft.memLeakPatched-y_np4plRNtso3GTV1RUb-Q==/lib/arm64/libunity.so (Camera_Get_Custom_PropMain()+36) (BuildId: 4add47ca148d41fe94977db941b2e4c3af1cd559)
09-06 13:55:25.289 28762 28813 E CRASH   :       #15 pc 000000000001b2bc  /data/data/com.king3soft.memLeakPatched/libIL2CPPResolver.so (InitGameThread()+292) (BuildId: 2ee20cf492949fe867e6e727de92ef2a1dc6d719)
09-06 13:55:25.289 28762 28813 E CRASH   :       #16 pc 000000000001b48c  /data/data/com.king3soft.memLeakPatched/libIL2CPPResolver.so (void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (*)()> >(void*)+44) (BuildId: 2ee20cf492949fe867e6e727de92ef2a1dc6d719)
09-06 13:55:25.289 28762 28813 E CRASH   :       #17 pc 00000000000d6b70  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: a2584ee8458a61d422edf24b4cd23b78)
09-06 13:55:25.289 28762 28813 E CRASH   :       #18 pc 0000000000074eac  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: a2584ee8458a61d422edf24b4cd23b78)

**Comment by geokar2006** [comment]
Not BNM issue, you trying call unity method from non unity thread.
