### ISSUE TITLE
unity 2020.3.x  arm64  crash

### ISSUE THREAD

**Issue by oobbb** [geokar2006/ByNameModding#21]
I haven't used anything yet

Just include bnm This leads to application crash
However, in the same version of arm32
bnm perfect work

please help me

**Comment by geokar2006** [comment]
Send BNM logs

**Comment by oobbb** [comment]
************* Crash Head ****************
Time Of Crash      : 2022_09_07-16_59_02
Device Manufacturer: Xiaomi
Device Model       : M2012K11AC
Android Version    : 12
Android SDK        : 31
App VersionName    : 2.60.5
App VersionCode    : 300
************* Crash Head ****************

java.lang.Error: FATAL EXCEPTION [UnityMain]
Unity version     : 2020.3.34f1
Device model      : Xiaomi M2012K11AC
Device fingerprint: Redmi/alioth/alioth:12/SKQ1.211006.001/V13.0.3.0.SKHCNXM:user/release-keys
Build Type        : Release
Scripting Backend : IL2CPP
ABI               : arm64-v8a
Strip Engine Code : true

Caused by: java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2020.3.34f1 (9a4c9c70452b)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
Build fingerprint: 'Redmi/alioth/alioth:12/SKQ1.211006.001/V13.0.3.0.SKHCNXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2022-09-07 16:59:02+0800
pid: 19154, tid: 19292, name: UnityMain  >>> com.aniplex.fategrandorder <<<
uid: 10896
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x32
Cause: null pointer dereference
    x0  00000077a02be390  x1  0000000000000000  x2  0000007a6f9fdb20  x3  0000007a654e4c41
    x4  0000000000000255  x5  0000007790000010  x6  0000000000000046  x7  747261502e656e69
    x8  0000000000000000  x9  0000000000000002  x10 00000077a02c3538  x11 0000000000000002
    x12 0000000000000020  x13 0000000000000000  x14 0000000000000018  x15 0000007a7c245c08
    x16 0000007a6578c948  x17 0000007b98124654  x18 00000000e843421b  x19 00000077a02be390
    x20 0000007a6f9fdb20  x21 0000000000000000  x22 b4000077f23ac138  x23 0000000000000001
    x24 0000000000000000  x25 0000007a6f9fe600  x26 0000007a6f9fe604  x27 0000007a6f9fe600
    x28 0000007a6f9fe500  x29 0000007a6f9fde40
    sp  0000007a6f9fda80  lr  0000007a6484fd94  pc  0000007a6484fcc4

backtrace:
      #00 pc 0000000000212cc4  /data/app/~~loUksRLAeopspbQGNndWGA==/com.aniplex.fategrandorder-V2zxCzkY753tc8hzMapD1w==/lib/arm64/libunity.so (BuildId: 7a1522fb0440571745ca8536f5f255d8b721a935)
      #01 pc 0000000000212d90  /data/app/~~loUksRLAeopspbQGNndWGA==/com.aniplex.fategrandorder-V2zxCzkY753tc8hzMapD1w==/lib/arm64/libunity.so (BuildId: 7a1522fb0440571745ca8536f5f255d8b721a935)
      #02 pc 0000000000212f40  /data/app/~~loUksRLAeopspbQGNndWGA==/com.aniplex.fategrandorder-V2zxCzkY753tc8hzMapD1w==/lib/arm64/libunity.so (BuildId: 7a1522fb0440571745ca8536f5f255d8b721a935)
      #03 pc 00000000003f48a8  /data/app/~~loUksRLAeopspbQGNndWGA==/com.aniplex.fategrandorder-V2zxCzkY753tc8hzMapD1w==/lib/arm64/libunity.so (BuildId: 7a1522fb0440571745ca8536f5f255d8b721a935)
      #04 pc 0000000000c891ac  /data/app/~~loUksRLAeopspbQGNndWGA==/com.aniplex.fategrandorder-V2zxCzkY753tc8hzMapD1w==/lib/arm64/libil2cpp.so (BuildId: 267a60835506fcd1c2c6a25fb3bd1e2109e72ebf)
      #05 pc 0000000000afbb3c  /data/app/~~loUksRLAeopspbQGNndWGA==/com.aniplex.fategrandorder-V2zxCzkY753tc8hzMapD1w==/lib/arm64/libil2cpp.so (BuildId: 267a60835506fcd1c2c6a25fb3bd1e2109e72ebf)
      #06 pc 000000000033e574  /data/app/~~loUksRLAeopspbQGNndWGA==/com.aniplex.fategrandorder-V2zxCzkY753tc8hzMapD1w==/lib/arm64/libunity.so (BuildId: 7a1522fb0440571745ca8536f5f255d8b721a935)
      #07 pc 00000000003421d0  /data/app/~~loUksRLAeopspbQGNndWGA==/com.aniplex.fategrandorder-V2zxCzkY753tc8hzMapD1w==/lib/arm64/libunity.so (BuildId: 7a1522fb0440571745ca8536f5f255d8b721a935)
      #08 pc 00000000003577c4  /data/app/~~loUksRLAeopspbQGNndWGA==/com.aniplex.fategrandorder-V2zxCzkY753tc8hzMapD1w==/lib/arm64/libunity.so (BuildId: 7a1522fb0440571745ca8536f5f255d8b721a935)
      #09 pc 0000000000221afc  /data/app/~~loUksRLAeopspbQGNndWGA==/com.aniplex.fategrandorder-V2zxCzkY753tc8hzMapD1w==/lib/arm64/libunity.so (BuildId: 7a1522fb0440571745ca8536f5f255d8b721a935)
      #10 pc 000000000029c088  /data/app/~~loUksRLAeopspbQGNndWGA==/com.aniplex.fategrandorder-V2zxCzkY753tc8hzMapD1w==/lib/arm64/libunity.so (BuildId: 7a1522fb0440571745ca8536f5f255d8b721a935)
      #11 pc 000000000029c0bc  /data/app/~~loUksRLAeopspbQGNndWGA==/com.aniplex.fategrandorder-V2zxCzkY753tc8hzMapD1w==/lib/arm64/libunity.so (BuildId: 7a1522fb0440571745ca8536f5f255d8b721a935)
      #12 pc 000000000029c300  /data/app/~~loUksRLAeopspbQGNndWGA==/com.aniplex.fategrandorder-V2zxCzkY753tc8hzMapD1w==/lib/arm64/libunity.so (BuildId: 7a1522fb0440571745ca8536f5f255d8b721a935)
      #13 pc 00000000003bb14c  /data/app/~~loUksRLAeopspbQGNndWGA==/com.aniplex.fategrandorder-V2zxCzkY753tc8hzMapD1w==/lib/arm64/libunity.so (BuildId: 7a1522fb0440571745ca8536f5f255d8b721a935)
      #14 pc 00000000003d0f94  /data/app/~~loUksRLAeopspbQGNndWGA==/com.aniplex.fategrandorder-V2zxCzkY753tc8hzMapD1w==/lib/arm64/libunity.so (BuildId: 7a1522fb0440571745ca8536f5f255d8b721a935)
      #15 pc 0000000000222244  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: fe3937ecd54810f2c0342e5633a5d7a7)
      #16 pc 0000000000212520  /apex/com.android.art/lib64/libart.so (nterp_helper+4016) (BuildId: fe3937ecd54810f2c0342e5633a5d7a7)
      #17 pc 00000000002115a4  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: fe3937ecd54810f2c0342e5633a5d7a7)
      #18 pc 00000000004fecd0  /system/framework/arm64/boot-framework.oat (BuildId: f9f84cdb09cbc24393a8f4b50cd7cb3266e1b8bf)

	at libunity.0x212cc4(Native Method)
	at libunity.0x212d90(Native Method)
	at libunity.0x212f40(Native Method)
	at libunity.0x3f48a8(Native Method)
	at libil2cpp.0xc891ac(Native Method)
	at libil2cpp.0xafbb3c(Native Method)
	at libunity.0x33e574(Native Method)
	at libunity.0x3421d0(Native Method)
	at libunity.0x3577c4(Native Method)
	at libunity.0x221afc(Native Method)
	at libunity.0x29c088(Native Method)
	at libunity.0x29c0bc(Native Method)
	at libunity.0x29c300(Native Method)
	at libunity.0x3bb14c(Native Method)
	at libunity.0x3d0f94(Native Method)
	at libart.art_quick_generic_jni_trampoline(art_quick_generic_jni_trampoline:148)
	at libart.nterp_helper(nterp_helper:4016)
	at libart.nterp_helper(nterp_helper:52)
	at boot-framework.0x4fecd0(Native Method)

**Comment by geokar2006** [comment]
Logs by tag: "ByNameModding"

**Comment by oobbb** [comment]
I'm not good at using logcat

this is my game : https://drive.google.com/file/d/1-3A5RXhXQNTHpF6FMD6PGJCSqmPo6PxH/view?usp=drivesdk

this is my source : https://drive.google.com/file/d/1-4g0dVyo1nEqJyOJS81i0h2F5veewHct/view?usp=drivesdk

**Comment by geokar2006** [comment]
> I'm not good at using logcat
> 
> this is my game : https://drive.google.com/file/d/1-3A5RXhXQNTHpF6FMD6PGJCSqmPo6PxH/view?usp=drivesdk
> 
> this is my source : https://drive.google.com/file/d/1-4g0dVyo1nEqJyOJS81i0h2F5veewHct/view?usp=drivesdk



I have sent a request.

**Comment by oobbb** [comment]
ok

**Comment by geokar2006** [comment]
Sorry for late fix, I was busy. But on this commit game work with BNM

**Comment by oobbb** [comment]
Successful work
thank you very much！
