### ISSUE TITLE
Sir pls help me.  cant hook field  

### ISSUE THREAD

**Issue by wwwww56** [geokar2006/ByNameModding#24]
your example.cpp don't have hook field

i hook like:

HOOK(FPSController.GetFieldByName(OBFUSCATE_BNM("Update")).GetOffset(), Update, old_Update); 

and it crash

pls give one example  which can hook field

Thank you very much!

**Comment by wwwww56** [comment]
i mean hook field just like : float、int、double...

**Comment by geokar2006** [comment]
You can't hook field, you can only get or set it. From Examples.cpp
• [Define field](https://github.com/geokar2006/ByNameModding/blob/fed1a8efeaaa56e67b8f779ff543395dcbdd40ab/Examples.cpp#L59)
• [Find field](https://github.com/geokar2006/ByNameModding/blob/fed1a8efeaaa56e67b8f779ff543395dcbdd40ab/Examples.cpp#L176)
• [Get field](https://github.com/geokar2006/ByNameModding/blob/fed1a8efeaaa56e67b8f779ff543395dcbdd40ab/Examples.cpp#L66)

**Comment by wwwww56** [comment]
> You can't hook field, you can only get or set it. From Examples.cpp • [Define field](https://github.com/geokar2006/ByNameModding/blob/fed1a8efeaaa56e67b8f779ff543395dcbdd40ab/Examples.cpp#L59) • [Find field](https://github.com/geokar2006/ByNameModding/blob/fed1a8efeaaa56e67b8f779ff543395dcbdd40ab/Examples.cpp#L176) • [Get field](https://github.com/geokar2006/ByNameModding/blob/fed1a8efeaaa56e67b8f779ff543395dcbdd40ab/Examples.cpp#L66)

so how can i set it,  example i want to set that field CoolTime = 0 , and how to do ?

**Comment by geokar2006** [comment]
`CoolTime` static?

**Comment by wwwww56** [comment]
public float CoolTime  or private float CoolTime

**Comment by geokar2006** [comment]
You need instance of class where field placed

**Comment by wwwww56** [comment]
in class SkillManager

**Comment by wwwww56** [comment]
no namespace

**Comment by geokar2006** [comment]
I have dump.cs or DummyDll?

**Comment by wwwww56** [comment]
yes  you have telegram ? i contact on it

**Comment by wwwww56** [comment]
[dump.cs.txt](https://github.com/geokar2006/ByNameModding/files/9865841/dump.cs.txt)

**Comment by wwwww56** [comment]
sir this is .cs files

**Comment by wwwww56** [comment]
![JM) @B~D_Q8YW_VFVAK@(N0](https://user-images.githubusercontent.com/98441603/197930851-e35d1097-176a-4bc0-8077-938f3231a64c.png)

**Comment by wwwww56** [comment]
i want set these three fields value to 0

**Comment by geokar2006** [comment]
I have only one idea, hook CreateSkill, and change  fields in it.
```cpp
BNM::Field<float> skillCooldown;
void *(*old_CreateSkill)(int, int);
void *CreateSkill(int skillT, int skillId) {
    auto skill = old_CreateSkill(skillT, skillId); // Get created Skill
    skillCooldown(skill) = 0.f; // Set skillCooldown to zero
    return skill; // Return modded skill
}
```

**Comment by wwwww56** [comment]
OK  thanks  sir   i will try it
