### ISSUE TITLE
sir  Hook field  There's still a problem

### ISSUE THREAD

**Issue by wwwww56** [geokar2006/ByNameModding#25]
BNM::Field<float> skillCooldown;
void *(*old_CreateSkill)(int, int);
void *CreateSkill(int skillT, int skillId) {
    auto skill = old_CreateSkill(skillT, skillId); // Get created Skill
    skillCooldown(skill) = 0.f; // Set skillCooldown to zero
    return skill; // Return modded skill
}

-------------
sir  this way  unless。its has bug ,  cant use

**Comment by geokar2006** [comment]
![изображение](https://user-images.githubusercontent.com/54073773/197982937-e4f87c6a-28fa-4a6a-b17e-400daf34a320.png)

**Comment by wwwww56** [comment]
i konw this  ,NO that type problem  

i hook like you,,  but  in game  that skill button is gone  ,invisible

**Comment by wwwww56** [comment]
game link：https://apkpure.com/tw/%E5%A1%94%E9%98%B2%E4%B8%89%E5%9C%8B%E5%BF%97/com.bigbull.tdsgtw

**Comment by wwwww56** [comment]
hope  you can try~

**Comment by wwwww56** [comment]
because i try many days

**Comment by wwwww56** [comment]
> Add a void*
> 
> example :
> 
> void * (*old_CreateSkill)(void * in,int, int); void * CreateSkill(void * in,int skillT, int skillId)

yes it has.  but cant work

**Comment by oobbb** [comment]
> > Add a void*
> > example :
> > void * (*old_CreateSkill)(void * in,int, int); void * CreateSkill(void * in,int skillT, int skillId)
> 
> yes it has. but cant work

Try to replace a new function

**Comment by wwwww56** [comment]
> > > Add a void*
> > > example :
> > > void * (*old_CreateSkill)(void * in,int, int); void * CreateSkill(void * in,int skillT, int skillId)
> > 
> > 
> > yes it has. but cant work
> 
> Try to replace a new function

i try  but the same
