### ISSUE TITLE
please add field how to set value~

### ISSUE THREAD

**Issue by wwwww56** [geokar2006/ByNameModding#26]
please add field how to set value~

**Comment by geokar2006** [comment]
```cpp
Field<float> static_float_field;
Field<float> float_field;

// ....
static_float_field = 0.f;
float_field(instance) = 0.f;
```

**Comment by geokar2006** [comment]
[Set example in Examples.cpp](https://github.com/geokar2006/ByNameModding/blob/c9e275608a917f0bcb0a7315492ff77d7a87911b/Examples.cpp#L86)

**Comment by YummyBacon5** [comment]
Can you please stop making useless posts
