### ISSUE TITLE
Как получить оффсет метода, находящися в классе, который внутри другого класса?) 

### ISSUE THREAD

**Issue by akamaized20287** [geokar2006/ByNameModding#3]
Я хочу сделать мод на игру Among Us с этой утилитой.

Есть класс:
  HatManager
    Update
    Start
      ...
       ..
   
 А там - есть это:
     public sealed class <>c

Там же, есть метод отвечающий за шляпы и т.д. Есть способ, как получить этот метод?)

**Comment by akamaized20287** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/80401984/124758584-9ff02980-df26-11eb-8dd3-1a722bae7aa9.png)

**Comment by geokar2006** [comment]
`auto HatManager_c = LoadClass("", "HatManager.<>c", true); // true - новый метод использующий global-metadata.dat`
Дальше уже можешь искать свои методы (будет использоваться новый способ). Если класс будет не найден то допиши это `if ((std::string("HatManager").find(std::string(_name) != std::string::npos) LOGIBNM("Found: %s", name)` в ByNameModding.h между 125 и 126 строками и проверь логи.

**Comment by akamaized20287** [comment]
спасибо огромное
