### ISSUE TITLE
Method like public int GetCurrency(CurrencyType type) { }

### ISSUE THREAD

**Issue by Mahmoud-GMG** [geokar2006/ByNameModding#30]
Methods like these can't be auto update..

public int GetCurrency(CurrencyType type) { }
public bool CheckSideImpact(ImpactFrameState impactState) { }
![Uploading Picsart_22-12-11_12-25-48-552.jpg…]()

**Comment by Mahmoud-GMG** [comment]
![Uploading Picsart_22-12-11_12-25-48-552.jpg…]()

**Comment by geokar2006** [comment]
JPGs are broken, and I think you just do something wrong.

**Comment by Mahmoud-GMG** [comment]
No error i fixed it
