### ISSUE TITLE
How to hook subclasses

### ISSUE THREAD

**Issue by chiteroman** [geokar2006/ByNameModding#31]
I have this class:
![image](https://user-images.githubusercontent.com/98092901/208304139-6e24326b-28ab-4c6b-88af-2e1e2e819052.png)
Which contains a subclass:
![image](https://user-images.githubusercontent.com/98092901/208304190-5df13d14-b3fb-4255-b511-b83d2da6696a.png)
![image](https://user-images.githubusercontent.com/98092901/208304213-a83db91d-00f1-4947-9176-0e670c69a630.png)

How can I load that class? I tried this:
```c++
Property<int> TotalDamage;

auto DamageData = LoadClass("", "SkillActionBase.DamageData");
TotalDamage = DamageData.GetPropertyByName("TotalDamage");
```

But I get this error:
`Class: [].[SkillActionBase.DamageData] - not found (without dll)`

How can I solve this? Thanks.

**Comment by geokar2006** [comment]
```cpp
Property<int> TotalDamage;

auto SkillActionBase = LoadClass("", "SkillActionBase");
auto DamageData = SkillActionBase.GetInnerClass("DamageData");
TotalDamage = DamageData.GetPropertyByName("TotalDamage");
```
