### ISSUE TITLE
BNM doesn't use `il2cpp_image_get_class`

### ISSUE THREAD

**Issue by YummyBacon5** [geokar2006/ByNameModding#32]
If a game has `il2cpp_image_get_class` then BNM will [apparently use it](/geokar2006/ByNameModding/blob/master/ByNameModding/BNM.cpp#L992), this makes `Image$$GetTypes` never be assigned to, but this function is [still used in the code](/geokar2006/ByNameModding/blob/master/ByNameModding/BNM.cpp#L38), causing a crash. I assume that `il2cpp_image_get_class` was meant to be used instead in these places

**Comment by geokar2006** [comment]
It work if user has c++17 and upper and don't defined `BNM_DISABLE_NEW_CLASSES 1` [here](https://github.com/geokar2006/ByNameModding/blob/c9e275608a917f0bcb0a7315492ff77d7a87911b/ByNameModding/BNM.cpp#L581), but otherwise yes, it never assigned. I will fix this, thx for reporting this issue.
