### ISSUE TITLE
大佬当我使用BNM去于LGL的模板结合之后在一个游戏刚启动后就会闪退

### ISSUE THREAD

**Issue by xiaoao666** [geokar2006/ByNameModding#33]
我将这个ByNameModding于LGL的mod模板结合，去做游戏改装，发现游戏会在刚启动的时候就闪退，
LGL模板的报错如下，希望能够被解决
************* Crash Head ****************
Time Of Crash      : 2023_02_04-14_08_11
Device Manufacturer: Xiaomi
Device Model       : M2004J7AC
Android Version    : 11
Android SDK        : 30
App VersionName    : 103.8.6
App VersionCode    : 1030806
************* Crash Head ****************

java.lang.Error: FATAL EXCEPTION [UnityMain]
Unity version     : 2021.3.9f1
Device model      : Xiaomi M2004J7AC
Device fingerprint: Redmi/atom/atom:11/RP1A.200720.011/22.1.13:user/release-keys
Build Type        : Release
Scripting Backend : IL2CPP
ABI               : arm64-v8a
Strip Engine Code : true

Caused by: java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2021.3.9f1 (987e3296728e)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
Build fingerprint: 'Redmi/atom/atom:11/RP1A.200720.011/22.1.13:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-02-04 14:08:10+0800
pid: 26016, tid: 26096, name: UnityMain  >>> com.proximabeta.nikke <<<
uid: 10790
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7dc
Cause: null pointer dereference
    x0  0000006ecb222906  x1  0000006ee30cd918  x2  0000000000000028  x3  0000000000000088
    x4  00000000000000e0  x5  0000000000000020  x6  00000000000000b0  x7  0000000000000090
    x8  0000006f553e6400  x9  0000000000000001  x10 0000000000000000  x11 0000006f553005cc
    x12 0000000000000005  x13 0000006f55300634  x14 000000003b21f150  x15 0000000022f0693f
    x16 0000006edac31c9c  x17 00000000000007dc  x18 0000006ec9ffa000  x19 0000006edac32a4c
    x20 0000006eca257ba0  x21 0000006eca258580  x22 0000006eca2580f0  x23 0000006eca25a000
    x24 0000006f54e48480  x25 0000006eca25a000  x26 0000000000000018  x27 0000006eca2580f0
    x28 0000006ecb2a0bc5  x29 0000006eca257b90
    sp  0000006eca257b80  lr  0000006ee788a7e8  pc  00000000000007dc

**Comment by geokar2006** [comment]
I don't know Chinese well, so please write in English, translators don't translate the text well. Also sorry for the late reply, I've been busy lately.
As for the crash, are you setting the unity version in the settings and are you using the new class system?
