### ISSUE TITLE
How can I hook a class with <T> operator

### ISSUE THREAD

**Issue by chiteroman** [geokar2006/ByNameModding#34]
I have this class:
![image](https://user-images.githubusercontent.com/98092901/218548231-ae97cdf7-700d-4bc5-b18d-824e359e5d5d.png)

And I want to hook the method "Instance" to get the instance of MobManager. Something like this: `TargetableListManagerBase<MobManager>`

MobManager is another class which I have already hook it.

Is it possible to do this and get the instance? Thanks.

**Comment by geokar2006** [comment]
Just use GetPropertyByName with Mob manager class. 
```cpp
BNM::LoadClass MobManager(OBFUSCATE_BNM(""), OBFUSCATE_BNM("MobManager"));
BNM::Property<void*> MobManager$$Instance = MobManager.GetPropertyByName(OBFUSCATE_BNM("Instance"));
```
BNM automatically finding methods in parent class of it not found in base.

**Comment by chiteroman** [comment]
Works like a charm, thank you!
