### ISSUE TITLE
Geokar2006

### ISSUE THREAD

**Issue by Tyndrahack** [geokar2006/ByNameModding#35]
Hello bro. I need your with BNM. Help me pls my tg- @shooter_mans

**Comment by geokar2006** [comment]
I don't have TG, so describe your problem here.

**Comment by Tyndrahack** [comment]
Can you give me your VK, I'll describe the problem there?

**Comment by geokar2006** [comment]
I don't have VK too.

**Comment by Tyndrahack** [comment]
Do you have any means of communication?

**Comment by geokar2006** [comment]
Github issues only

**Comment by Tyndrahack** [comment]
Will we communicate here?

**Comment by geokar2006** [comment]
Just describe your problem

**Comment by Tyndrahack** [comment]
I need your help with bypass standoff 2,i can pay money

**Comment by Tyndrahack** [comment]
Are you here?

**Comment by geokar2006** [comment]
No more online games for bypassing.

**Comment by Tyndrahack** [comment]
Will you help me?

**Comment by geokar2006** [comment]
No

**Comment by Tyndrahack** [comment]
You already had the crawl sources for previous versions

**Comment by Tyndrahack** [comment]
Can you sell them to me

**Comment by geokar2006** [comment]
I lost almost all sources when reinstalling Windows. So I don't have old sources.

**Comment by Tyndrahack** [comment]
You can return to tg or vk?

**Comment by Tyndrahack** [comment]
You are very experienced and cool, I would like to learn something from you

**Comment by geokar2006** [comment]
> You can return to tg or vk?

No

**Comment by Tyndrahack** [comment]
Let's chat with you here

**Comment by geokar2006** [comment]
Github not a messenger

**Comment by Tyndrahack** [comment]
Вы очень опытный,я могу у вас научиться чему-то?

**Comment by Tyndrahack** [comment]
You are very experienced, can I learn something from you?

**Comment by geokar2006** [comment]
> Вы очень опытный,я могу у вас научиться чему-то?

Не можешь

**Comment by Tyndrahack** [comment]
Вы русский?

**Comment by Tyndrahack** [comment]
Are you here?

**Comment by geokar2006** [comment]
> Вы русский?

...

**Comment by Tyndrahack** [comment]
Я не знал этого изначально,поэтому я и переспрашиваю.

**Comment by Tyndrahack** [comment]
Как в бнм создать апдейт,и там же менять поле?

**Comment by geokar2006** [comment]
> Как в бнм создать апдейт,и там же менять поле?

Файл [Examples.cpp](https://github.com/geokar2006/ByNameModding/blob/master/Examples.cpp) полон примеров

**Comment by Tyndrahack** [comment]
НЕ МАТЕРИСЬ!
