### ISSUE TITLE
External?

### ISSUE THREAD

**Issue by Rednick16** [geokar2006/ByNameModding#4]
Would this work externally? Can’t seem to get it to work, works internally seems like

any idea if it works externally?

**Comment by geokar2006** [comment]
I've never hack externally. I need see how to get lib there. It's just that the usual findLibrary is not suitable for use in ByNameModding, it is dlopen that is needed.

**Comment by Rednick16** [comment]
I don’t do much android modding but im sure its the same for ios/android create a buffer and read from our buffer. buffer would be be created from ReadProccessMemory And stored locally byNameModding would be able to access it
