### ISSUE TITLE
Hooking Method when both are very identical ??

### ISSUE THREAD

**Issue by Gourov** [geokar2006/ByNameModding#6]
Hello brother ,
is it possible to hook something like this ?
![Screenshot_2](https://user-images.githubusercontent.com/65507457/130518997-9579b0b8-ddda-4346-abb5-8d9f12c7be2a.png)
![Screenshot_3](https://user-images.githubusercontent.com/65507457/130519005-35c4b07a-4deb-4e50-b762-3bc234a29a6b.png)

Both have same number of params and same param names . Only difference is param type. Can hook this ?? If not will you add something for this types of methods ?

**Comment by geokar2006** [comment]
Hello, I will add method for searching methods by type along with the next big update.

**Comment by Gourov** [comment]
> 
> 
> Hello, I will add method for searching methods by type along with the next big update.

Thats great . Any idea when the update will come ?? Also it will be great if you add Dictionary Template , Decrypting Obscured type template in this project. You can easily find them out there.

**Comment by geokar2006** [comment]
New update already in progress. At the moment, what will be in the update is a secret. (Except your issue)
